// <auto-generated />
using System;
using DoomsdayLogs.InfraORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoomsdayLogs.InfraORM.Migrations
{
    [DbContext(typeof(DoomsdayLogsDbContext))]
    [Migration("20230613194345_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoomsdayLogs.Domain.LogModule.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogClassName")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("LogData")
                        .HasColumnType("NTEXT");

                    b.Property<DateTime?>("LogDateTime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("LogDescription")
                        .HasColumnType("NVARCHAR(350)");

                    b.Property<string>("LogHelp")
                        .HasColumnType("NVARCHAR(350)");

                    b.Property<string>("LogLine")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("LogMethodName")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("LogName")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("LogType")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("LogDB", (string)null);
                });

            modelBuilder.Entity("DoomsdayLogs.Domain.ProjectModule.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProjectName")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("ProjectVersion")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("ProjectDB", (string)null);
                });

            modelBuilder.Entity("DoomsdayLogs.Domain.LogModule.Log", b =>
                {
                    b.HasOne("DoomsdayLogs.Domain.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
